### DISCUSSION TITLE
How to connect a with SpiceDB running inside a docker compose

### DISCUSSION THREAD

**Discussion by FernandoArteaga** [authzed/spicedb#1644] [Q&A] [answered]
Hi, I'm playing around and getting familiar with SpiceDB,

I have a service A that connects with SpiceDB.

My SpiceDB always runs in docker.

I can connect with SpiceDB from my machine (when I run the API locally). But once I dockerize the `service A` and add it to the docker-compose I can't connect them.

Any idea if I'm missing any configuration/flag?

Thanks

---

This is the docker-compose
```yaml
version: '3'

services:
  spicedb:
    image: authzed/spicedb:1.27.0
    command: "serve"
    restart: always
    ports:
      - "9351:50051"
    environment:
      SPICEDB_GRPC_PRESHARED_KEY: ${SPICEDB_KEY}
      SPICEDB_DATASTORE_ENGINE: postgres
      SPICEDB_DATASTORE_CONN_URI: postgres://${DB_USERNAME}:${DB_PASSWORD}@postgres:5432/spicedb?sslmode=${DB_SSL_MODE}
      SPICEDB_METRICS_ENABLED: FALSE

  service-a:
    image: service-a:local
    restart: always
    ports:
      - "9430:80"
    environment:
      API_HOST: "0.0.0.0"
      API_PORT: 80
      SPICEDB_HOST: spicedb
      SPICEDB_PORT: 50051
      # SPICEDB_PORT: 9351
      SPICEDB_API_KEY: ${SPICEDB_KEY}
    depends_on:
      - spicedb
```

This is the error I get from the container when I try to connect using the port `9351`:
```
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:172.19.0.17:9351: Failed to connect to remote host: Connection refused"
	debug_error_string = "UNKNOWN:failed to connect to all addresses; last error: UNKNOWN: ipv4:172.19.0.17:9351: Failed to connect to remote host: Connection refused {created_time:"2023-11-12T00:07:38.907016766+00:00", grpc_status:14}"
```
This is the error I get from the container when I try to connect using the port `50051`:
```
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:172.19.0.17:50051: Endpoint is neither UDS or TCP loopback address."
	debug_error_string = "UNKNOWN:failed to connect to all addresses; last error: UNKNOWN: ipv4:172.19.0.17:50051: Endpoint is neither UDS or TCP loopback address. {grpc_status:14, created_time:"2023-11-12T00:09:35.210919941+00:00"}"
```

**Comment by vroldanbet** [comment, marked as answer]
As you noted, you are most likely hitting https://github.com/authzed/authzed-py/issues/89. Here is the simplest example I could come up with that works and does not involve a python client:

```yaml
version: "3"

services:
  spicedb:
    image: "authzed/spicedb"
    command: "serve"
    restart: "always"
    ports:
      - "50051:50051"
    environment:
      - "SPICEDB_GRPC_PRESHARED_KEY=foobar"
      - "SPICEDB_DATASTORE_ENGINE=memory"
  my_service:
    image: authzed/zed:latest
    command: ["schema", "read", "--insecure=true", "--endpoint", "spicedb:50051", "--token", "foobar"]
    restart: unless-stopped
    depends_on:
      - spicedb
```
