### ISSUE TITLE
reading credentials from file option

### ISSUE THREAD

**Issue by mstrYoda** [authzed/spicedb#1082]
Currently, SpiceDB takes credentials as program args or env variables which is makes it quite hard to manage in Kubernetes.

If we set db credentials as env vars on deployments it exposes our credentials (all cluster users can see deployment manifest), same as deployment args.

WDYT about having a credential file option?

**Comment by jzelinskie** [comment]
Did you know about secrefRefs for environment variables in Kubernetes?

```yaml
...
    spec: 
      containers: 
        - env: 
            - name: myenv
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: mysecretKey
```
