### ISSUE TITLE
An update of mysql migration scripts in version 1.20.0 breaks checkPermission requests

### ISSUE THREAD

**Issue by TheRealDashu** [authzed/spicedb#1369]
Since this update https://github.com/authzed/spicedb/blob/94a077f52330936f3410f636a5e7b00d90cacb52/internal/datastore/mysql/migrations/zz_migration.0005_extend_object_id.go

We are getting sql failures when using the checkPermission Endpoint of the authzed/api/v1

This is the error message:
`error performing check: unable to query tuples: Error 1267: Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8mb4_general_ci,COERCIBLE) for operation '='`

That is because the relation_tuple table get converted to a different encoding. In this case latin1 while the rest is encoded in utf8 i think.

```
func adjustObjectIDLength(t *tables) string {
	return fmt.Sprintf(
		`ALTER TABLE %s
		CONVERT TO CHARACTER SET latin1,
		MODIFY object_id VARCHAR(1024) NOT NULL,
		MODIFY userset_object_id VARCHAR(1024) NOT NULL;`,
		t.RelationTuple(),
	)
}
```
**CONVERT TO CHARACTER SET latin1,**

We are úsing this spiceDB configuration in a docker-compose. Variables in this snippet dont reflect our real configuration bút were replaced with defaults:

```
spicedb:
    <<: *logging-defaults
    # For issues use tag v1.19.1-debug
    image: authzed/spicedb:v1.19.1
    command: "serve"
    restart: "on-failure"
    ports:
      - "8080:8080"
      - "9090:9090"
      - "50051:50051"
    environment:
      - SPICEDB_GRPC_PRESHARED_KEY=foobar
      - SPICEDB_DATASTORE_ENGINE=mysql
      - "SPICEDB_DATASTORE_CONN_URI=root:secret@tcp(mysql:3306)/spicedb?parseTime=true"
      - SPICEDB_GRPC_TLS_CERT_PATH=/certs/server.crt
      - SPICEDB_GRPC_TLS_KEY_PATH=/certs/server.key
    depends_on:
      - "spicedb_migrate"
    networks:
      - db
    volumes:
      - ./certs:/certs
    env_file:
      - ./shared/env/mysql.env
      - ./shared/env/mysqluser.env
  spicedb_migrate:
    # For issues use tag v1.19.1-debug
    image: authzed/spicedb:v1.19.1
    command: "migrate head"
    restart: "on-failure"
    networks:
      - db
    environment:
      - SPICEDB_DATASTORE_ENGINE=mysql
      - "SPICEDB_DATASTORE_CONN_URI=root:secret@tcp(mysql:3306)/spicedb?parseTime=true"
    depends_on:
      - "mysql"
```
And as an application we are using a C++20 application for which we generated c++ code out of the authzed/api/v1 proto files.

Everything works for us with v1.19.1
