### ISSUE TITLE
Telemetry collector error after restart

### ISSUE THREAD

**Issue by teawithfruit** [authzed/spicedb#1529]
### What platforms are affected?

linux, macOS

### What architectures are affected?

amd64, arm64

### Steps to Reproduce

1. Start `spicedb` with the following docker compose file:

```yaml
version: '3.8'

services:
  postgres:
    image: postgres:14.7
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DATABASES: spicedb
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  spicedb-migrate:
    image: authzed/spicedb:v1.25.0
    command: migrate head
    restart: on-failure
    depends_on:
      - postgres
    environment:
      - 'SPICEDB_DATASTORE_ENGINE=postgres'
      - 'SPICEDB_DATASTORE_CONN_URI=postgres://postgres:password@postgres:5432/spicedb?sslmode=disable'

  spicedb:
    image: authzed/spicedb:v1.25.0
    ports:
      - '9090:9090'
      - '50051:50051'
    healthcheck:
      test:
        ['CMD', '/usr/local/bin/grpc_health_probe', '-addr', 'spicedb:50051']
      interval: 30s
      timeout: 3s
      retries: 5
    command: serve
    restart: on-failure
    depends_on:
      - spicedb-migrate
    environment:
      - 'SPICEDB_GRPC_PRESHARED_KEY=TOKEN_TOKEN_TOKEN'
      - 'SPICEDB_DATASTORE_ENGINE=postgres'
      - 'SPICEDB_DATASTORE_CONN_URI=postgres://postgres:password@postgres:5432/spicedb?sslmode=disable'

volumes:
  postgres-data:
```
You have to create the `spicedb` database by your own inside postgres.

2. Stop the docker environment
3. Restart the environment

Do you got any ideas?

### Expected Result

The server should start properly after an environment restart.

### Actual Result

I got the following error:

```json
{
  "level": "error",
  "error": "unable to initialize telemetry collector: unable to query DB stats: unable to query unique ID: no rows in result set",
  "time": "2023-09-08T07:49:23Z",
  "message": "terminated with errors"
}
```
