### ISSUE TITLE
Can't migrate with Postgresql 

### ISSUE THREAD

**Issue by luanxuechao** [authzed/spicedb#1926]
### What platforms are affected?

others

### What architectures are affected?

others

### What SpiceDB version are you using?
PG version: 15
I use the docker-compose, docker image:
authzed/spicedb                                                             latest                            013fba16affd   13 days ago     94.3MB
docker-compose.yml
```
version: "3.8"

services:
  spicedb-migrate:
    image: authzed/spicedb
    command: migrate head
    restart: on-failure
    environment:
      - "SPICEDB_DATASTORE_ENGINE=postgres"
      - "SPICEDB_DATASTORE_CONN_URI=postgres://*****/spicedb?sslmode=disable"
```

### Steps to Reproduce

1.docker-compose up
 

### Expected Result

It should be migrate success

### Actual Result

stop with unkonwn issue:
```
spicedb-migrate_1  | {"level":"info","statement":"UPDATE caveat \n\t\tSET deleted_xid = deleted_transaction::text::xid8,\n\t\tcreated_xid = created_transaction::text::xid8\n\t\tWHERE (name, created_transaction, deleted_transaction) IN (\n\t\t\tSELECT name, created_transaction, deleted_transaction\n\t\t\tFROM caveat\n\t\t\tWHERE created_xid IS NULL\n\t\t\tLIMIT 1000\n\t\t\tFOR UPDATE\n\t\t);","time":"2024-06-06T10:18:28Z","message":"starting backfill"}
spicedb-migrate_1  | {"level":"info","from":"backfill-xid-add-indices","to":"add-xid-constraints","time":"2024-06-06T10:18:31Z","message":"migrating"}
spicedb-migrate_1  | {"level":"info","from":"add-xid-constraints","to":"drop-id-constraints","time":"2024-06-06T10:18:33Z","message":"migrating"}
spicedb-migrate_1  | {"level":"info","from":"drop-id-constraints","to":"drop-bigserial-ids","time":"2024-06-06T10:18:34Z","message":"migrating"}
spicedb-migrate_1  | {"level":"info","from":"drop-bigserial-ids","to":"add-gc-covering-index","time":"2024-06-06T10:18:35Z","message":"migrating"}
spicedb-migrate_1  | {"level":"info","from":"add-gc-covering-index","to":"add-tuned-gc-index","time":"2024-06-06T10:18:36Z","message":"migrating"}
spicedb-migrate_1  | {"level":"info","from":"add-tuned-gc-index","to":"add-rel-by-alive-resource-relation-subject","time":"2024-06-06T10:18:38Z","message":"migrating"}
```
It stops at the script: add-tuned-gc-index.
