### ISSUE TITLE
database is no longer valid and must be remigrated

### ISSUE THREAD

**Issue by batazor** [authzed/spicedb#2091]
### What platforms are affected?

linux

### What architectures are affected?

amd64

### What SpiceDB version are you using?

v1.37.0

### Steps to Reproduce

```
apiVersion: authzed.com/v1alpha1
kind: SpiceDBCluster
metadata:
  name: shortlink
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  config:
    replicas: 1
    datastoreEngine: postgres
  secretName: shortlink-spicedb-config
  patches:
    - kind: Deployment
      patch:
        spec:
          template:
            metadata:
              annotations:
                sidecar.istio.io/inject: "false"
            spec:
              containers:
                - name: spicedb
                  image: 'ghcr.io/authzed/spicedb:v1.37.0'
                  resources:
                    requests:
                      memory: "128Mi"
                      cpu: "50m"
                    limits:
                      memory: "512Mi"
                      cpu: "200m"
                  env:
                    - name: SPICEDB_DATASTORE_CONN_URI
                      valueFrom:
                        secretKeyRef:
                          name: spicedb-postgres-pguser-spicedb
                          key: uri
                    - name: SPICEDB_DISPATCH_CACHE_METRICS
                      value: "true"
                    - name: SPICEDB_DISPATCH_CLUSTER_METRICS
                      value: "true"
                    - name: SPICEDB_NS_CACHE_METRICS
                      value: "true"
                    - name: SPICEDB_METRICS_ENABLED
                      value: "true"
                    - name: SPICEDB_OTEL_PROVIDER
                      value: otlpgrpc
                    - name: SPICEDB_OTEL_SAMPLE_RATIO
                      value: "1"
                    - name: OTEL_EXPORTER_OTLP_ENDPOINT
                      value: "http://grafana-tempo.grafana:4317"
    - kind: Job
      patch:
        spec:
          template:
            metadata:
              annotations:
                sidecar.istio.io/inject: "false"
            spec:
              containers:
                - name: migrate
                  image: 'ghcr.io/authzed/spicedb:v1.37.0'
                  env:
                    - name: SPICEDB_DATASTORE_CONN_URI
                      valueFrom:
                        secretKeyRef:
                          name: spicedb-postgres-pguser-spicedb
                          key: uri
```

### Expected Result

correct install

### Actual Result

```
{"level":"warn","datastoreReady":false,"time":"2024-10-12T22:17:04Z","message":"datastore failed readiness checks: datastore is not migrated: currently at revision `add-rel-by-alive-resource-relation-subject`, but requires `create-relationships-counters-table`. Please run `spicedb migrate`. If you have previously run `TRUNCATE`, this database is no longer valid and must be remigrated. See: https://spicedb.dev/d/truncate-unsupported"}

````
