### ISSUE TITLE
Create quickstart examples

### ISSUE THREAD

**Issue by bryanhuhta** [authzed/spicedb#469]
I think it could be valuable to have a quickstart example to get a basic SpiceDB instance running for each datastore. This would be convenient for folks who are trying to quickly spin up SpiceDB and experiment. For example, for getting SpiceDB with Postgres running, a Docker Compose file like this could be provided:

```yaml
version: '3'

services:
  spicedb:
    image: quay.io/authzed/spicedb
    command: serve
    restart: always
    ports:
      - 50051:50051
    environment:
      - SPICEDB_GRPC_PRESHARED_KEY=foobar
      - SPICEDB_DATASTORE_ENGINE=postgres
      - SPICEDB_DATASTORE_CONN_URI=postgres://postgres:password@pg:5432/spicedb?sslmode=disable
    depends_on:
      - migrate
      - postgres
  migrate:
    image: quay.io/authzed/spicedb
    command: migrate head
    restart: on-failure
    environment:
      - SPICEDB_DATASTORE_ENGINE=postgres
      - SPICEDB_DATASTORE_CONN_URI=postgres://postgres:password@pg:5432/spicedb?sslmode=disable
    depends_on:
      - postgres
  pg:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=spicedb
```

While it's not difficult for someone to create these files themselves, it would be convenient if there were working examples that allowed someone could clone the repo and run right away.
