### ISSUE TITLE
Basic k8s example doesn't specify RBAC required to use kuberesolver dispatch

### ISSUE THREAD

**Issue by jakedt** [authzed/spicedb#499]
Need to add the following:

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spicedb
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: watch-service
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["endpoints"]
  verbs: ["get", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spicedb-watch-service
  namespace: default
subjects:
- kind: ServiceAccount
  name: spicedb
roleRef:
  kind: Role
  name: watch-service
  apiGroup: rbac.authorization.k8s.io
```
